// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations.Pg
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260409222635_SınavIndexAdded")]
    partial class SınavIndexAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Core.Entities.Concrete.GroupClaim", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "ClaimId");

                    b.ToTable("GroupClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "tr-TR",
                            IsActive = true,
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en-US",
                            IsActive = true,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Core.Entities.Concrete.MobileLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSend")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId", "Provider");

                    b.ToTable("MobileLogins");
                });

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.DenemeSinavSonucu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BosSayisi")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DersId")
                        .HasColumnType("integer");

                    b.Property<int>("DogruSayisi")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ToplamNet")
                        .HasColumnType("numeric");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("YanlisSayisi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.ToTable("DenemeSinavSonucus");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.DenemeSinavi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SinavId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SinavId");

                    b.HasIndex("UserId");

                    b.ToTable("DenemeSinavis");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("SinavBolumId")
                        .HasColumnType("integer");

                    b.Property<int>("SinavId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SinavBolumId");

                    b.HasIndex("SinavId");

                    b.ToTable("Derses");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.Konu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DersId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.ToTable("Konus");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.KullaniciKonuIlerleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("KonuId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KonuId");

                    b.HasIndex("UserId");

                    b.ToTable("KullaniciKonuIlerlemes");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.KullaniciSinav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HedefPuan")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SinavId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SinavId");

                    b.HasIndex("UserId");

                    b.ToTable("KullaniciSinavs");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.Sinav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DogruyuGoturenYanlisSay")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KısaAd")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Sinavs");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.SinavBolum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Isim")
                        .HasColumnType("text");

                    b.Property<int>("SinavId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SinavId");

                    b.ToTable("SinavBolums");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Translate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LangId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Translates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Login",
                            IsActive = true,
                            LangId = 1,
                            Value = "Giriş"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Email",
                            IsActive = true,
                            LangId = 1,
                            Value = "E posta"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Password",
                            IsActive = true,
                            LangId = 1,
                            Value = "Parola"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Update",
                            IsActive = true,
                            LangId = 1,
                            Value = "Güncelle"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Delete",
                            IsActive = true,
                            LangId = 1,
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 6,
                            Code = "UsersGroups",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kullanıcının Grupları"
                        },
                        new
                        {
                            Id = 7,
                            Code = "UsersClaims",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kullanıcının Yetkileri"
                        },
                        new
                        {
                            Id = 8,
                            Code = "Create",
                            IsActive = true,
                            LangId = 1,
                            Value = "Yeni"
                        },
                        new
                        {
                            Id = 9,
                            Code = "Users",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kullanıcılar"
                        },
                        new
                        {
                            Id = 10,
                            Code = "Groups",
                            IsActive = true,
                            LangId = 1,
                            Value = "Gruplar"
                        },
                        new
                        {
                            Id = 11,
                            Code = "Login",
                            IsActive = true,
                            LangId = 2,
                            Value = "Login"
                        },
                        new
                        {
                            Id = 12,
                            Code = "Email",
                            IsActive = true,
                            LangId = 2,
                            Value = "Email"
                        },
                        new
                        {
                            Id = 13,
                            Code = "Password",
                            IsActive = true,
                            LangId = 2,
                            Value = "Password"
                        },
                        new
                        {
                            Id = 14,
                            Code = "Update",
                            IsActive = true,
                            LangId = 2,
                            Value = "Update"
                        },
                        new
                        {
                            Id = 15,
                            Code = "Delete",
                            IsActive = true,
                            LangId = 2,
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 16,
                            Code = "UsersGroups",
                            IsActive = true,
                            LangId = 2,
                            Value = "User's Groups"
                        },
                        new
                        {
                            Id = 17,
                            Code = "UsersClaims",
                            IsActive = true,
                            LangId = 2,
                            Value = "User's Claims"
                        },
                        new
                        {
                            Id = 18,
                            Code = "Create",
                            IsActive = true,
                            LangId = 2,
                            Value = "Create"
                        },
                        new
                        {
                            Id = 19,
                            Code = "Users",
                            IsActive = true,
                            LangId = 2,
                            Value = "Users"
                        },
                        new
                        {
                            Id = 20,
                            Code = "Groups",
                            IsActive = true,
                            LangId = 2,
                            Value = "Groups"
                        },
                        new
                        {
                            Id = 21,
                            Code = "OperationClaim",
                            IsActive = true,
                            LangId = 1,
                            Value = "Operasyon Yetkileri"
                        },
                        new
                        {
                            Id = 22,
                            Code = "OperationClaim",
                            IsActive = true,
                            LangId = 2,
                            Value = "Operation Claim"
                        },
                        new
                        {
                            Id = 23,
                            Code = "Languages",
                            IsActive = true,
                            LangId = 1,
                            Value = "Diller"
                        },
                        new
                        {
                            Id = 24,
                            Code = "Languages",
                            IsActive = true,
                            LangId = 2,
                            Value = "Languages"
                        },
                        new
                        {
                            Id = 25,
                            Code = "TranslateWords",
                            IsActive = true,
                            LangId = 1,
                            Value = "Dil Çevirileri"
                        },
                        new
                        {
                            Id = 26,
                            Code = "TranslateWords",
                            IsActive = true,
                            LangId = 2,
                            Value = "Translate Words"
                        },
                        new
                        {
                            Id = 27,
                            Code = "Management",
                            IsActive = true,
                            LangId = 1,
                            Value = "Yönetim"
                        },
                        new
                        {
                            Id = 28,
                            Code = "Management",
                            IsActive = true,
                            LangId = 2,
                            Value = "Management"
                        },
                        new
                        {
                            Id = 29,
                            Code = "AppMenu",
                            IsActive = true,
                            LangId = 1,
                            Value = "Uygulama"
                        },
                        new
                        {
                            Id = 30,
                            Code = "AppMenu",
                            IsActive = true,
                            LangId = 2,
                            Value = "Application"
                        },
                        new
                        {
                            Id = 31,
                            Code = "Added",
                            IsActive = true,
                            LangId = 1,
                            Value = "Başarıyla Eklendi."
                        },
                        new
                        {
                            Id = 32,
                            Code = "Added",
                            IsActive = true,
                            LangId = 2,
                            Value = "Successfully Added."
                        },
                        new
                        {
                            Id = 33,
                            Code = "Updated",
                            IsActive = true,
                            LangId = 1,
                            Value = "Başarıyla Güncellendi."
                        },
                        new
                        {
                            Id = 34,
                            Code = "Updated",
                            IsActive = true,
                            LangId = 2,
                            Value = "Successfully Updated."
                        },
                        new
                        {
                            Id = 35,
                            Code = "Deleted",
                            IsActive = true,
                            LangId = 1,
                            Value = "Başarıyla Silindi."
                        },
                        new
                        {
                            Id = 36,
                            Code = "Deleted",
                            IsActive = true,
                            LangId = 2,
                            Value = "Successfully Deleted."
                        },
                        new
                        {
                            Id = 37,
                            Code = "OperationClaimExists",
                            IsActive = true,
                            LangId = 1,
                            Value = "Bu operasyon izni zaten mevcut."
                        },
                        new
                        {
                            Id = 38,
                            Code = "OperationClaimExists",
                            IsActive = true,
                            LangId = 2,
                            Value = "This operation permit already exists."
                        },
                        new
                        {
                            Id = 39,
                            Code = "StringLengthMustBeGreaterThanThree",
                            IsActive = true,
                            LangId = 1,
                            Value = "Lütfen En Az 3 Karakterden Oluşan Bir İfade Girin."
                        },
                        new
                        {
                            Id = 40,
                            Code = "StringLengthMustBeGreaterThanThree",
                            IsActive = true,
                            LangId = 2,
                            Value = "Please Enter A Phrase Of At Least 3 Characters."
                        },
                        new
                        {
                            Id = 41,
                            Code = "CouldNotBeVerifyCid",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kimlik No Doğrulanamadı."
                        },
                        new
                        {
                            Id = 42,
                            Code = "CouldNotBeVerifyCid",
                            IsActive = true,
                            LangId = 2,
                            Value = "Could not be verify Citizen Id"
                        },
                        new
                        {
                            Id = 43,
                            Code = "VerifyCid",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kimlik No Doğrulandı."
                        },
                        new
                        {
                            Id = 44,
                            Code = "VerifyCid",
                            IsActive = true,
                            LangId = 2,
                            Value = "Verify Citizen Id"
                        },
                        new
                        {
                            Id = 45,
                            Code = "AuthorizationsDenied",
                            IsActive = true,
                            LangId = 1,
                            Value = "Yetkiniz olmayan bir alana girmeye çalıştığınız tespit edildi."
                        },
                        new
                        {
                            Id = 46,
                            Code = "AuthorizationsDenied",
                            IsActive = true,
                            LangId = 2,
                            Value = "It has been detected that you are trying to enter an area that you do not have authorization."
                        },
                        new
                        {
                            Id = 47,
                            Code = "UserNotFound",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kimlik Bilgileri Doğrulanamadı. Lütfen Yeni Kayıt Ekranını kullanın."
                        },
                        new
                        {
                            Id = 48,
                            Code = "UserNotFound",
                            IsActive = true,
                            LangId = 2,
                            Value = "Credentials Could Not Verify. Please use the New Registration Screen."
                        },
                        new
                        {
                            Id = 49,
                            Code = "PasswordError",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kimlik Bilgileri Doğrulanamadı, Kullanıcı adı ve/veya parola hatalı."
                        },
                        new
                        {
                            Id = 50,
                            Code = "PasswordError",
                            IsActive = true,
                            LangId = 2,
                            Value = "Credentials Failed to Authenticate, Username and / or password incorrect."
                        },
                        new
                        {
                            Id = 51,
                            Code = "SuccessfulLogin",
                            IsActive = true,
                            LangId = 1,
                            Value = "Sisteme giriş başarılı."
                        },
                        new
                        {
                            Id = 52,
                            Code = "SuccessfulLogin",
                            IsActive = true,
                            LangId = 2,
                            Value = "Login to the system is successful."
                        },
                        new
                        {
                            Id = 53,
                            Code = "SendMobileCode",
                            IsActive = true,
                            LangId = 1,
                            Value = "Lütfen Size SMS Olarak Gönderilen Kodu Girin!"
                        },
                        new
                        {
                            Id = 54,
                            Code = "SendMobileCode",
                            IsActive = true,
                            LangId = 2,
                            Value = "Please Enter The Code Sent To You By SMS!"
                        },
                        new
                        {
                            Id = 55,
                            Code = "NameAlreadyExist",
                            IsActive = true,
                            LangId = 1,
                            Value = "Oluşturmaya Çalıştığınız Nesne Zaten Var."
                        },
                        new
                        {
                            Id = 56,
                            Code = "NameAlreadyExist",
                            IsActive = true,
                            LangId = 2,
                            Value = "The Object You Are Trying To Create Already Exists."
                        },
                        new
                        {
                            Id = 57,
                            Code = "WrongCID",
                            IsActive = true,
                            LangId = 1,
                            Value = "Vatandaşlık No Sistemimizde Bulunamadı. Lütfen Yeni Kayıt Oluşturun!"
                        },
                        new
                        {
                            Id = 58,
                            Code = "WrongCID",
                            IsActive = true,
                            LangId = 2,
                            Value = "Citizenship Number Not Found In Our System. Please Create New Registration!"
                        },
                        new
                        {
                            Id = 59,
                            Code = "CID",
                            IsActive = true,
                            LangId = 1,
                            Value = "Vatandaşlık No"
                        },
                        new
                        {
                            Id = 60,
                            Code = "CID",
                            IsActive = true,
                            LangId = 2,
                            Value = "Citizenship Number"
                        },
                        new
                        {
                            Id = 61,
                            Code = "PasswordEmpty",
                            IsActive = true,
                            LangId = 1,
                            Value = "Parola boş olamaz!"
                        },
                        new
                        {
                            Id = 62,
                            Code = "PasswordEmpty",
                            IsActive = true,
                            LangId = 2,
                            Value = "Password can not be empty!"
                        },
                        new
                        {
                            Id = 63,
                            Code = "PasswordLength",
                            IsActive = true,
                            LangId = 1,
                            Value = "Minimum 8 Karakter Uzunluğunda Olmalıdır!"
                        },
                        new
                        {
                            Id = 64,
                            Code = "PasswordLength",
                            IsActive = true,
                            LangId = 2,
                            Value = "Must be at least 8 characters long! "
                        },
                        new
                        {
                            Id = 65,
                            Code = "PasswordUppercaseLetter",
                            IsActive = true,
                            LangId = 1,
                            Value = "En Az 1 Büyük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = 66,
                            Code = "PasswordUppercaseLetter",
                            IsActive = true,
                            LangId = 2,
                            Value = "Must Contain At Least 1 Capital Letter!"
                        },
                        new
                        {
                            Id = 67,
                            Code = "PasswordLowercaseLetter",
                            IsActive = true,
                            LangId = 1,
                            Value = "En Az 1 Küçük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = 68,
                            Code = "PasswordLowercaseLetter",
                            IsActive = true,
                            LangId = 2,
                            Value = "Must Contain At Least 1 Lowercase Letter!"
                        },
                        new
                        {
                            Id = 69,
                            Code = "PasswordDigit",
                            IsActive = true,
                            LangId = 1,
                            Value = "En Az 1 Rakam İçermelidir!"
                        },
                        new
                        {
                            Id = 70,
                            Code = "PasswordDigit",
                            IsActive = true,
                            LangId = 2,
                            Value = "It Must Contain At Least 1 Digit!"
                        },
                        new
                        {
                            Id = 71,
                            Code = "PasswordSpecialCharacter",
                            IsActive = true,
                            LangId = 1,
                            Value = "En Az 1 Simge İçermelidir!"
                        },
                        new
                        {
                            Id = 72,
                            Code = "PasswordSpecialCharacter",
                            IsActive = true,
                            LangId = 2,
                            Value = "Must Contain At Least 1 Symbol!"
                        },
                        new
                        {
                            Id = 73,
                            Code = "SendPassword",
                            IsActive = true,
                            LangId = 1,
                            Value = "Yeni Parolanız E-Posta Adresinize Gönderildi."
                        },
                        new
                        {
                            Id = 74,
                            Code = "SendPassword",
                            IsActive = true,
                            LangId = 2,
                            Value = "Your new password has been sent to your e-mail address."
                        },
                        new
                        {
                            Id = 75,
                            Code = "InvalidCode",
                            IsActive = true,
                            LangId = 1,
                            Value = "Geçersiz Bir Kod Girdiniz!"
                        },
                        new
                        {
                            Id = 76,
                            Code = "InvalidCode",
                            IsActive = true,
                            LangId = 2,
                            Value = "You Entered An Invalid Code!"
                        },
                        new
                        {
                            Id = 77,
                            Code = "SmsServiceNotFound",
                            IsActive = true,
                            LangId = 1,
                            Value = "SMS Servisine Ulaşılamıyor."
                        },
                        new
                        {
                            Id = 78,
                            Code = "SmsServiceNotFound",
                            IsActive = true,
                            LangId = 2,
                            Value = "Unable to Reach SMS Service."
                        },
                        new
                        {
                            Id = 79,
                            Code = "TrueButCellPhone",
                            IsActive = true,
                            LangId = 1,
                            Value = "Bilgiler doğru. Cep telefonu gerekiyor."
                        },
                        new
                        {
                            Id = 80,
                            Code = "TrueButCellPhone",
                            IsActive = true,
                            LangId = 2,
                            Value = "The information is correct. Cell phone is required."
                        },
                        new
                        {
                            Id = 81,
                            Code = "TokenProviderException",
                            IsActive = true,
                            LangId = 1,
                            Value = "Token Provider boş olamaz!"
                        },
                        new
                        {
                            Id = 82,
                            Code = "TokenProviderException",
                            IsActive = true,
                            LangId = 2,
                            Value = "Token Provider cannot be empty!"
                        },
                        new
                        {
                            Id = 83,
                            Code = "Unknown",
                            IsActive = true,
                            LangId = 1,
                            Value = "Bilinmiyor!"
                        },
                        new
                        {
                            Id = 84,
                            Code = "Unknown",
                            IsActive = true,
                            LangId = 2,
                            Value = "Unknown!"
                        },
                        new
                        {
                            Id = 85,
                            Code = "NewPassword",
                            IsActive = true,
                            LangId = 1,
                            Value = "Yeni Parola:"
                        },
                        new
                        {
                            Id = 86,
                            Code = "NewPassword",
                            IsActive = true,
                            LangId = 2,
                            Value = "New Password:"
                        },
                        new
                        {
                            Id = 87,
                            Code = "ChangePassword",
                            IsActive = true,
                            LangId = 1,
                            Value = "Parola Değiştir"
                        },
                        new
                        {
                            Id = 88,
                            Code = "ChangePassword",
                            IsActive = true,
                            LangId = 2,
                            Value = "Change Password"
                        },
                        new
                        {
                            Id = 89,
                            Code = "Save",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = 90,
                            Code = "Save",
                            IsActive = true,
                            LangId = 2,
                            Value = "Save"
                        },
                        new
                        {
                            Id = 91,
                            Code = "GroupName",
                            IsActive = true,
                            LangId = 1,
                            Value = "Grup Adı"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GroupName",
                            IsActive = true,
                            LangId = 2,
                            Value = "Group Name"
                        },
                        new
                        {
                            Id = 93,
                            Code = "FullName",
                            IsActive = true,
                            LangId = 1,
                            Value = "Tam Adı"
                        },
                        new
                        {
                            Id = 94,
                            Code = "FullName",
                            IsActive = true,
                            LangId = 2,
                            Value = "Full Name"
                        },
                        new
                        {
                            Id = 95,
                            Code = "Address",
                            IsActive = true,
                            LangId = 1,
                            Value = "Adres"
                        },
                        new
                        {
                            Id = 96,
                            Code = "Address",
                            IsActive = true,
                            LangId = 2,
                            Value = "Address"
                        },
                        new
                        {
                            Id = 97,
                            Code = "Notes",
                            IsActive = true,
                            LangId = 1,
                            Value = "Notlar"
                        },
                        new
                        {
                            Id = 98,
                            Code = "Notes",
                            IsActive = true,
                            LangId = 2,
                            Value = "Notes"
                        },
                        new
                        {
                            Id = 99,
                            Code = "ConfirmPassword",
                            IsActive = true,
                            LangId = 1,
                            Value = "Parolayı Doğrula"
                        },
                        new
                        {
                            Id = 100,
                            Code = "ConfirmPassword",
                            IsActive = true,
                            LangId = 2,
                            Value = "Confirm Password"
                        },
                        new
                        {
                            Id = 101,
                            Code = "Code",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kod"
                        },
                        new
                        {
                            Id = 102,
                            Code = "Code",
                            IsActive = true,
                            LangId = 2,
                            Value = "Code"
                        },
                        new
                        {
                            Id = 103,
                            Code = "Alias",
                            IsActive = true,
                            LangId = 1,
                            Value = "Görünen Ad"
                        },
                        new
                        {
                            Id = 104,
                            Code = "Alias",
                            IsActive = true,
                            LangId = 2,
                            Value = "Alias"
                        },
                        new
                        {
                            Id = 105,
                            Code = "Description",
                            IsActive = true,
                            LangId = 1,
                            Value = "Açıklama"
                        },
                        new
                        {
                            Id = 106,
                            Code = "Description",
                            IsActive = true,
                            LangId = 2,
                            Value = "Description"
                        },
                        new
                        {
                            Id = 107,
                            Code = "Value",
                            IsActive = true,
                            LangId = 1,
                            Value = "Değer"
                        },
                        new
                        {
                            Id = 108,
                            Code = "Value",
                            IsActive = true,
                            LangId = 2,
                            Value = "Value"
                        },
                        new
                        {
                            Id = 109,
                            Code = "LangCode",
                            IsActive = true,
                            LangId = 1,
                            Value = "Dil Kodu"
                        },
                        new
                        {
                            Id = 110,
                            Code = "LangCode",
                            IsActive = true,
                            LangId = 2,
                            Value = "Lang Code"
                        },
                        new
                        {
                            Id = 111,
                            Code = "Name",
                            IsActive = true,
                            LangId = 1,
                            Value = "Adı"
                        },
                        new
                        {
                            Id = 112,
                            Code = "Name",
                            IsActive = true,
                            LangId = 2,
                            Value = "Name"
                        },
                        new
                        {
                            Id = 113,
                            Code = "MobilePhones",
                            IsActive = true,
                            LangId = 1,
                            Value = "Cep Telefonu"
                        },
                        new
                        {
                            Id = 114,
                            Code = "MobilePhones",
                            IsActive = true,
                            LangId = 2,
                            Value = "Mobile Phone"
                        },
                        new
                        {
                            Id = 115,
                            Code = "NoRecordsFound",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kayıt Bulunamadı"
                        },
                        new
                        {
                            Id = 116,
                            Code = "NoRecordsFound",
                            IsActive = true,
                            LangId = 2,
                            Value = "No Records Found"
                        },
                        new
                        {
                            Id = 117,
                            Code = "Required",
                            IsActive = true,
                            LangId = 1,
                            Value = "Bu alan zorunludur!"
                        },
                        new
                        {
                            Id = 118,
                            Code = "Required",
                            IsActive = true,
                            LangId = 2,
                            Value = "This field is required!"
                        },
                        new
                        {
                            Id = 119,
                            Code = "Permissions",
                            IsActive = true,
                            LangId = 1,
                            Value = "Permissions"
                        },
                        new
                        {
                            Id = 120,
                            Code = "Permissions",
                            IsActive = true,
                            LangId = 2,
                            Value = "İzinler"
                        },
                        new
                        {
                            Id = 121,
                            Code = "GroupList",
                            IsActive = true,
                            LangId = 1,
                            Value = "Grup Listesi"
                        },
                        new
                        {
                            Id = 122,
                            Code = "GroupList",
                            IsActive = true,
                            LangId = 2,
                            Value = "Group List"
                        },
                        new
                        {
                            Id = 123,
                            Code = "GrupPermissions",
                            IsActive = true,
                            LangId = 1,
                            Value = "Grup Yetkileri"
                        },
                        new
                        {
                            Id = 124,
                            Code = "GrupPermissions",
                            IsActive = true,
                            LangId = 2,
                            Value = "Grup Permissions"
                        },
                        new
                        {
                            Id = 125,
                            Code = "Add",
                            IsActive = true,
                            LangId = 1,
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 126,
                            Code = "Add",
                            IsActive = true,
                            LangId = 2,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 127,
                            Code = "UserList",
                            IsActive = true,
                            LangId = 1,
                            Value = "Kullanıcı Listesi"
                        },
                        new
                        {
                            Id = 128,
                            Code = "UserList",
                            IsActive = true,
                            LangId = 2,
                            Value = "User List"
                        },
                        new
                        {
                            Id = 129,
                            Code = "OperationClaimList",
                            IsActive = true,
                            LangId = 1,
                            Value = "Yetki Listesi"
                        },
                        new
                        {
                            Id = 130,
                            Code = "OperationClaimList",
                            IsActive = true,
                            LangId = 2,
                            Value = "OperationClaim List"
                        },
                        new
                        {
                            Id = 131,
                            Code = "LanguageList",
                            IsActive = true,
                            LangId = 1,
                            Value = "Dil Listesi"
                        },
                        new
                        {
                            Id = 132,
                            Code = "LanguageList",
                            IsActive = true,
                            LangId = 2,
                            Value = "Language List"
                        },
                        new
                        {
                            Id = 133,
                            Code = "TranslateList",
                            IsActive = true,
                            LangId = 1,
                            Value = "Dil Çeviri Listesi"
                        },
                        new
                        {
                            Id = 134,
                            Code = "TranslateList",
                            IsActive = true,
                            LangId = 2,
                            Value = "Translate List"
                        },
                        new
                        {
                            Id = 135,
                            Code = "LogList",
                            IsActive = true,
                            LangId = 1,
                            Value = "İşlem Kütüğü"
                        },
                        new
                        {
                            Id = 136,
                            Code = "LogList",
                            IsActive = true,
                            LangId = 2,
                            Value = "LogList"
                        },
                        new
                        {
                            Id = 137,
                            Code = "DeleteConfirm",
                            IsActive = true,
                            LangId = 1,
                            Value = "Emin misiniz?"
                        },
                        new
                        {
                            Id = 138,
                            Code = "DeleteConfirm",
                            IsActive = true,
                            LangId = 2,
                            Value = "Are you sure?"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("MobilePhones")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateContactDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Email");

                    b.HasIndex("MobilePhones");

                    b.HasIndex("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserClaim", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.DenemeSinavSonucu", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Project.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.DenemeSinavi", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Project.Sinav", "Sinav")
                        .WithMany()
                        .HasForeignKey("SinavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinav");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.Ders", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Project.SinavBolum", "SinavBolum")
                        .WithMany()
                        .HasForeignKey("SinavBolumId");

                    b.HasOne("Core.Entities.Concrete.Project.Sinav", "Sinav")
                        .WithMany()
                        .HasForeignKey("SinavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinav");

                    b.Navigation("SinavBolum");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.Konu", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Project.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.KullaniciKonuIlerleme", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Project.Konu", "Konu")
                        .WithMany()
                        .HasForeignKey("KonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.KullaniciSinav", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Project.Sinav", "Sinav")
                        .WithMany()
                        .HasForeignKey("SinavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinav");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Project.SinavBolum", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Project.Sinav", "Sinav")
                        .WithMany()
                        .HasForeignKey("SinavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinav");
                });
#pragma warning restore 612, 618
        }
    }
}
